version: '3'

volumes:
  # MongoDB Data
  devradar-data:
    driver: local

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - devradar-data:/data/db
